#!/bin/sh

cd /var/www/ietf.org/rfc

while true
do
	nice rsync -avz rsync.ietf.org::rfc /var/www/ietf.org/rfc/
	for rfc in rfc*.txt
	do
		idx=${rfc%.txt}.idx
		if [ $rfc -nt $idx ]
		then
			rfc2idx $rfc $idx
		fi
	done
	sleep 86400
done

